baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Ailan Cerqueira Batista'
theme = 'mini'

defaultContentLanguage = "en"
# themesDir = "../../"
hasCJKLanguage = true
paginate = 3
# googleAnalytics = "your-google-analytics-id"
disqusShortname = "Ailan"

[permalinks]
posts = "/posts/:title/"

[markup.highlight]
guessSyntax = true
style = "emacs"

[markup.tableOfContents]
endLevel = 3
ordered = false
startLevel = 2

[markup.goldmark.renderer]
unsafe = true

[social]
github = "https://github.com/ailanBR"
twitter = "https://twitter.com/ailanLob"

[params]
author = "Ailan"
bio = "Software Engineer"
description = "My Blog"
enableRSS = false
enableComments = false
enableGoogleAnalytics = false
showToc = true
showPowerBy = true
math = false
hiddenPostSummaryInHomePage = false
copyright = ""
